dist: trusty
sudo: false
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: pypy3.5-5.8.0
cache:
  - pip
install:
  - pip install tox-travis
script:
  - tox
